# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Perform SolidInvoice installation tasks
  when: solidinvoice_enabled | bool
  tags:
    - setup-all
    - setup-solidinvoice
    - install-all
    - install-solidinvoice
  block:
    - name: Validate SolidInvoice configuration
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"
    - name: Install SolidInvoice
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"

- name: Perform tasks to print database credentials for SolidInvoice
  when: solidinvoice_enabled | bool
  tags:
    - print-db-credentials-solidinvoice
  block:
    - name: Print database credentials for SolidInvoice
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/print_db_credentials.yml"

- name: Perform SolidInvoice uninstallation tasks
  when: not solidinvoice_enabled | bool
  tags:
    - setup-all
    - setup-solidinvoice
  block:
    - name: Uninstall SolidInvoice
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
