# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Fail if SolidInvoice database type is set to `sqlite`
  when: "solidinvoice_database_type == 'sqlite'"
  ansible.builtin.set_fact:
    devture_playbook_runtime_messages_list: |
      {{
        devture_playbook_runtime_messages_list | default([])
        +
        [
          "Database credentials are not available for a SQLite database."
        ]
      }}

- name: Run if SolidInvoice database type is set to `mysql`
  when: "solidinvoice_database_type == 'mysql'"
  block:
    - name: Fail if required SolidInvoice + MySQL integration settings not defined
      ansible.builtin.fail:
        msg: >-
          You need to define a required configuration setting (`{{ item }}`) when `solidinvoice_database_type` is `mysql`
      when: "solidinvoice_database_type == 'mysql' and lookup('vars', item, default='') | string | length == 0"
      with_items:
        - solidinvoice_database_mysql_hostname
        - solidinvoice_database_mysql_password

    - name: Print SolidInvoice MySQL database credentials
      ansible.builtin.set_fact:
        devture_playbook_runtime_messages_list: |
          {{
            devture_playbook_runtime_messages_list | default([])
            +
            [
              "Here is your SolidInvoice MySQL database information:
              - database host: `" + solidinvoice_database_mysql_hostname + "`
              - database port: `" + solidinvoice_database_mysql_port + "`
              - database username: `" + solidinvoice_database_mysql_username + "`
              - database password: `" + solidinvoice_database_mysql_password + "`
              - database name: `" + solidinvoice_database_name + "`
              Enter these values on the installation wizard UI."
            ]
          }}

- name: Run if SolidInvoice database type is set to `postgres`
  when: "solidinvoice_database_type == 'postgres'"
  block:
    - name: Fail if required SolidInvoice + Postgres integration settings not defined
      ansible.builtin.fail:
        msg: >-
          You need to define a required configuration setting (`{{ item }}`) when `solidinvoice_database_type` is `postgres`
      when: "solidinvoice_database_type == 'postgres' and lookup('vars', item, default='') | string | length == 0"
      with_items:
        - solidinvoice_database_postgres_hostname
        - solidinvoice_database_postgres_password

    - name: Print SolidInvoice Postgres database credentials
      ansible.builtin.set_fact:
        devture_playbook_runtime_messages_list: |
          {{
            devture_playbook_runtime_messages_list | default([])
            +
            [
              "Here is your SolidInvoice Postgres database information:
              - database host: `" + solidinvoice_database_postgres_hostname + "`
              - database port: `" + solidinvoice_database_postgres_port + "`
              - database username: `" + solidinvoice_database_postgres_username + "`
              - database password: `" + solidinvoice_database_postgres_password + "`
              - database name: `" + solidinvoice_database_name + "`
              Enter these values on the installation wizard UI."
            ]
          }}
