# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Fail if farmOS database type is set to `sqlite`
  when: "farmos_database_type == 'sqlite'"
  ansible.builtin.set_fact:
    devture_playbook_runtime_messages_list: |
      {{
        devture_playbook_runtime_messages_list | default([])
        +
        [
          "Database credentials are not available for a SQLite database."
        ]
      }}

- name: Run if farmOS database type is set to `mysql`
  when: "farmos_database_type == 'mysql'"
  block:
    - name: Fail if required farmOS + MySQL integration settings not defined
      ansible.builtin.fail:
        msg: >-
          You need to define a required configuration setting (`{{ item }}`) when `farmos_database_type` is `mysql`
      when: "farmos_database_type == 'mysql' and lookup('vars', item, default='') | string | length == 0"
      with_items:
        - farmos_database_mysql_hostname
        - farmos_database_mysql_password

    - name: Print farmOS MySQL database credentials
      ansible.builtin.set_fact:
        devture_playbook_runtime_messages_list: |
          {{
            devture_playbook_runtime_messages_list | default([])
            +
            [
              "Here is your farmOS MySQL database information:
              - database name: `" + farmos_database_name + "`
              - database username: `" + farmos_database_mysql_username + "`
              - database password: `" + farmos_database_mysql_password + "`
              - database host: `" + farmos_database_mysql_hostname + ":" + farmos_database_mysql_port + "`
              Enter these values on the installation wizard UI.

              Table prefix does not have to be set."
            ]
          }}

- name: Run if farmOS database type is set to `postgres`
  when: "farmos_database_type == 'postgres'"
  block:
    - name: Fail if required farmOS + Postgres integration settings not defined
      ansible.builtin.fail:
        msg: >-
          You need to define a required configuration setting (`{{ item }}`) when `farmos_database_type` is `postgres`
      when: "farmos_database_type == 'postgres' and lookup('vars', item, default='') | string | length == 0"
      with_items:
        - farmos_database_postgres_hostname
        - farmos_database_postgres_password

    - name: Print farmOS Postgres database credentials
      ansible.builtin.set_fact:
        devture_playbook_runtime_messages_list: |
          {{
            devture_playbook_runtime_messages_list | default([])
            +
            [
              "Here is your farmOS Postgres database information:
              - database name: `" + farmos_database_name + "`
              - database username: `" + farmos_database_postgres_username + "`
              - database password: `" + farmos_database_postgres_password + "`
              - database host: `" + farmos_database_postgres_hostname + ":" + farmos_database_postgres_port + "`
              Enter these values on the installation wizard UI.

              Table prefix does not have to be set."
            ]
          }}
