# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
# The command to add the hostname to `trusted_host_patterns` on.settings.php: ansible-playbook -i inventory/hosts setup.yml --tags=trusted-host-solidinvoice

- name: Ensure SolidInvoice settings.php file writable
  ansible.builtin.file:
    path: "{{ solidinvoice_sites_path }}/default/settings.php"
    mode: "0750"
    owner: "{{ solidinvoice_uid }}"
    group: "{{ solidinvoice_gid }}"

- name: Ensure SolidInvoice hostname is added to `trusted_host_patterns` on settings.php
  ansible.builtin.blockinfile:
    path: "{{ solidinvoice_sites_path }}/default/settings.php"
    block: |
      $settings['trusted_host_patterns'] = [
       '^{{ solidinvoice_hostname | regex_escape() }}$',
      ];

- name: Ensure SolidInvoice settings.php non-writable
  ansible.builtin.file:
    path: "{{ solidinvoice_sites_path }}/default/settings.php"
    mode: "0444"
    owner: "{{ solidinvoice_uid }}"
    group: "{{ solidinvoice_gid }}"
